### ISSUE TITLE
Add meaningful error for CSV parsing when source_identifier column is not present

### ISSUE THREAD

**Issue by jeremyf** [samvera-labs/bulkrax#735]
```gherkin
Given a CSV Parser that has a source_identifier field
And a CSV that does not have a column for the source_identifier field
When I got to import that CSV
Then I should receive a meaningful error message indicating that I'm missing a required field
```

The [documentation on required fields](https://github.com/samvera-labs/bulkrax/wiki/CSV-Importer#required-fields) is something that should be enforced.

At present, if I have a CSV that lacks the source_identifier column, I get the following exception:

```shell
IndexError:
  string not matched
# ./app/models/concerns/bulkrax/has_matchers.rb:70:in `[]='
# ./app/models/concerns/bulkrax/has_matchers.rb:70:in `set_parsed_object_data'
# ./app/models/concerns/bulkrax/has_matchers.rb:55:in `block in add_metadata'
# ./app/models/concerns/bulkrax/has_matchers.rb:31:in `each'
# ./app/models/concerns/bulkrax/has_matchers.rb:31:in `add_metadata'
# ./app/models/bulkrax/csv_entry.rb:87:in `block in add_ingested_metadata'
# ./app/models/bulkrax/csv_entry.rb:85:in `each'
# ./app/models/bulkrax/csv_entry.rb:85:in `add_ingested_metadata' 
```

The exception is opaque in regards to the underlying problem.

**Comment by jeremyf** [comment]
I'm investigating this further, as there might be something more going on.
